/
arm_biquad_cascade_df1_fast_q31.o/
arm_biquad_cascade_df1_init_f32.o/
arm_biquad_cascade_df1_init_q15.o/
arm_biquad_cascade_df1_init_q31.o/
arm_biquad_cascade_df1_q15.o/
arm_biquad_cascade_df1_q31.o/
arm_biquad_cascade_df2t_init_f32.o/
arm_conv_fast_q15.o/
arm_conv_fast_q31.o/
arm_conv_partial_f32.o/
arm_conv_partial_fast_q15.o/
arm_conv_partial_fast_q31.o/
arm_conv_partial_q7.o/
arm_conv_partial_q15.o/
arm_conv_partial_q31.o/
arm_correlate_f32.o/
arm_correlate_fast_q15.o/
arm_correlate_fast_q31.o/
arm_correlate_q7.o/
arm_correlate_q15.o/
arm_correlate_q31.o/
arm_fir_decimate_f32.o/
arm_fir_decimate_fast_q15.o/
arm_fir_decimate_fast_q31.o/
arm_fir_decimate_init_f32.o/
arm_fir_decimate_init_q15.o/
arm_fir_decimate_init_q31.o/
arm_fir_decimate_q15.o/
arm_fir_decimate_q31.o/
arm_fir_fast_q15.o/
arm_fir_fast_q31.o/
arm_fir_init_f32.o/
arm_fir_init_q7.o/
arm_fir_init_q15.o/
arm_fir_init_q31.o/
arm_fir_interpolate_f32.o/
arm_fir_interpolate_init_f32.o/
arm_fir_interpolate_init_q15.o/
arm_fir_interpolate_init_q31.o/
arm_fir_interpolate_q15.o/
arm_fir_interpolate_q31.o/
arm_fir_lattice_f32.o/
arm_fir_lattice_init_f32.o/
arm_fir_lattice_init_q15.o/
arm_fir_lattice_init_q31.o/
arm_fir_lattice_q15.o/
arm_fir_lattice_q31.o/
arm_fir_sparse_f32.o/
arm_fir_sparse_init_f32.o/
arm_fir_sparse_init_q7.o/
arm_fir_sparse_init_q15.o/
arm_fir_sparse_init_q31.o/
arm_fir_sparse_q7.o/
arm_fir_sparse_q15.o/
arm_fir_sparse_q31.o/
arm_iir_lattice_f32.o/
arm_iir_lattice_init_f32.o/
arm_iir_lattice_init_q15.o/
arm_iir_lattice_init_q31.o/
arm_iir_lattice_q15.o/
arm_iir_lattice_q31.o/
arm_lms_init_f32.o/
arm_lms_init_q15.o/
arm_lms_init_q31.o/
arm_lms_norm_f32.o/
arm_lms_norm_init_f32.o/
arm_lms_norm_init_q15.o/
arm_lms_norm_init_q31.o/
arm_lms_norm_q15.o/
arm_lms_norm_q31.o/
arm_correlate_opt_q15.o/
arm_conv_opt_q7.o/
arm_conv_opt_q15.o/
arm_conv_partial_opt_q7.o/
arm_conv_partial_opt_q15.o/
arm_correlate_opt_q7.o/
arm_correlate_fast_opt_q15.o/
arm_conv_fast_opt_q15.o/
arm_conv_partial_fast_opt_q15.o/
arm_biquad_cascade_df2t_f32.o/
arm_biquad_cascade_df2t_f64.o/
arm_biquad_cascade_df2t_init_f64.o/
arm_biquad_cascade_stereo_df2t_f32.o/
arm_biquad_cascade_stereo_df2t_init_f32.o/
arm_mat_add_f32.o/
arm_mat_add_q15.o/
arm_mat_add_q31.o/
arm_mat_init_f32.o/
arm_mat_init_q15.o/
arm_mat_init_q31.o/
arm_mat_inverse_f32.o/
arm_mat_mult_f32.o/
arm_mat_mult_fast_q15.o/
arm_ma